### ISSUE TITLE
这里理论推导应该是负梯度方向啊，为什么这里用的是梯度方向，关键是结果还正确。

### ISSUE THREAD

**Issue by Brave731** [lawlite19/MachineLearning_Python#1]
https://github.com/lawlite19/MachineLearning_Python/blob/7fc56845e7ef008e5a28233d455f98fc82a77d18/NeuralNetwok/NeuralNetwork.py#L165

**Comment by lawlite19** [comment]
https://github.com/lawlite19/MachineLearning_Python/blob/7fc56845e7ef008e5a28233d455f98fc82a77d18/NeuralNetwok/NeuralNetwork.py#L46

优化代价函数时这里使用scipy 中的方法，传入的是梯度

**Comment by lawlite19** [comment]
函数如图
![image](https://user-images.githubusercontent.com/14356062/33202317-125294ba-d137-11e7-8486-05551eb3a819.png)

**Comment by Brave731** [comment]
@lawlite19 这个自然是明白的，我说的是误差反向传播时的梯度，用的是均方误差对权重的导数，这里西瓜书上明确写的是负梯度方向，和代码中的符号正好相反

**Comment by lawlite19** [comment]
所以这里只是求梯度啊

**Comment by Brave731** [comment]
![2017-11-24 17-22-55](https://user-images.githubusercontent.com/29353926/33203939-c4904e2e-d13c-11e7-9dc2-b9c434cdea83.png)
![img_1552](https://user-images.githubusercontent.com/29353926/33203952-ce5b52a0-d13c-11e7-9d35-b3479215d297.JPG)
![img_1553](https://user-images.githubusercontent.com/29353926/33203957-d016a6d0-d13c-11e7-8430-48dad874bc49.JPG)
这里标注的，最后一层的误差符号和西瓜书上的相反

**Comment by Brave731** [comment]
![Uploading 2017-11-24 17-22-55屏幕截图 (2).png…]()

**Comment by lawlite19** [comment]
上面不是说了，那个函数只要传入梯度，它自然会按负梯度方向优化

**Comment by Brave731** [comment]
老哥看来没明白我的意思，你说的传入梯度是损失函数的梯度，我说的是误差逆传播里的均方误差的梯度，最后一层的误差方向传播符号不对

**Comment by Brave731** [comment]
![2017-11-24 17-22-55 2](https://user-images.githubusercontent.com/29353926/33205241-2b4d3470-d141-11e7-91e3-d9e084539d97.png)

**Comment by Brave731** [comment]
谢谢你的解答，我理解是怎么回事了
