### ISSUE TITLE
LogisticRegression_scikit-learn.py

### ISSUE THREAD

**Issue by lawlietsoul** [lawlite19/MachineLearning_Python#11]
大神你好，非常感谢你写的这个python机器学习系列，受益良多！
今天在看LogisticRegression_scikit-learn.py时候，发现归一化那里，你使用了
`    # 归一化
    scaler = StandardScaler()
    scaler.fit(x_train)
    x_train = scaler.fit_transform(x_train)
    x_test = scaler.fit_transform(x_test)`
其中， scaler.fit(x_train)应该是不需要的吧?查了sklearn的文档，里面写道:
fit_transform(X[, y]) | Fit to data, then transform it.
而scaler.fit(x_train) 应该和scaler.transform(x_train)组合使用。
不知道理解的对不对，希望你有空的话可以帮忙看一下，感谢！
文档连接
http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

**Comment by lawlite19** [comment]
是的，多谢提出，之后做下修改。
