### ISSUE TITLE
关于nn_params的问题

### ISSUE THREAD

**Issue by W-void** [lawlite19/MachineLearning_Python#2]
为什么要将nn_params reshape来reshape去呢，不能直接向optimize.fmin_cg函数中传入它本来的shape吗

**Comment by lawlite19** [comment]
你可以看它函数的描述，必须要是一维的
![image](https://user-images.githubusercontent.com/14356062/33533966-7fb30756-d8df-11e7-8a37-48986435f2bd.png)

**Comment by W-void** [comment]
非常感谢
