### ISSUE TITLE
关于nnGradient函数的一个问题

### ISSUE THREAD

**Issue by W-void** [lawlite19/MachineLearning_Python#4]
Theta1[:,0] = 0;
Theta2[:,0] = 0;
函数的这个地方，这样会改变nnParams的值，会直接将bias置0，
我试了下如果先copy的话，acc会达到99%+

**Comment by lawlite19** [comment]
不好意思，最近有些忙刚看到。
是的，下面修改了Theta的值，nn_params也会一起修改，已做修改。

**Comment by W-void** [comment]
理解，大神一般都是忙的
