### ISSUE TITLE
bug？

### ISSUE THREAD

**Issue by Rouzip** [lawlite19/MachineLearning_Python#5]
https://github.com/lawlite19/MachineLearning_Python/blob/7eac77f7446a0c69bfb1a8be7da405895409d131/SVM/SVM_scikit-learn.py#L49
这一行构造等差数列写错？我觉得应该选取x轴的max和min吧

**Comment by lawlite19** [comment]
是的，已做修改
`
xp = np.linspace(np.min(X[:,0]),np.max(X[:,0]),100)
`
